name: Analyze Actions Billable Time
on:
  workflow_dispatch:
  pull_request:
    branches:
      - "feature/workflows"

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          ORG_NAME: "pavelpiha"
      - run: |
          npm install @octokit/rest @octokit/core
          node ./.github/scripts/analyze-billable-time.js
