name: Analyze Actions Billable Time
on:
  workflow_dispatch:
  pull_request:
    branches:
      - "feature/workflows"
      - "main"

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
        env:
          USER: "pavelpiha"
          # GITPAT: ${{secrets.GITPAT}}
          GITPAT: ${{secrets.GIT_PAT_FINE_GRAINED}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Install Dependencies
        run: npm install @octokit/rest @octokit/core
      - name: Run Script
        run: node ./.github/scripts/analyze-billable-time.js
